### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by lazyfred98** [Steel-Dev/ItemQualities#1]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like**
I would love to see a config, where i can toggle if i want the items i craft myself to be affected by the plugin.
In my opinion it would be nice if the loot i get from endcitys, dungeons, villagers etc would have qualities but the stuff i craft myself should be +-0 or it should get better the more i craft. 

**Additional context**

**Comment by Steel-Dev** [comment]
I can do that, not fully sure about the getting better the more you craft, I'll see what I can do
