### ISSUE TITLE
Fishing Rod receives quality, but not reforgeable

### ISSUE THREAD

**Issue by fahlur** [Steel-Dev/ItemQualities#12]
Fishing rods will have a quality but cant be reforged, I suspect its not suppose to have qualities?

**Comment by fahlur** [comment]
Bow had same issue, added to the config solved it for me. xD

**Comment by Steel-Dev** [comment]
Yeah, those items I forgot to add to the default list of item's that can be reforged. This was 'fixed' in the upcoming version (1.0.7)

**Comment by Steel-Dev** [comment]
Fixed in release 1.1.0!
