### ISSUE TITLE
Double drops destroy shulkers and items within

### ISSUE THREAD

**Issue by kvakkvak** [Steel-Dev/ItemQualities#14]
Name says it all, when you destroy shulkers with double drops instead of getting 2 you get nothing :(

**Comment by Steel-Dev** [comment]
This has been fixed. The fix will be coming with 1.0.7s release!

**Comment by kvakkvak** [comment]
Thank you very much :) Also you are unable to rename item even with quality being in lore. or it being in name. It always changes the name back to "Affix Tool"

**Comment by Steel-Dev** [comment]
I'm aware of this - this will be fixed in 1.0.7!

**Comment by Steel-Dev** [comment]
Fixed in release 1.1.0!
