### ISSUE TITLE
How can I change the plugin content to another language myself？

### ISSUE THREAD

**Issue by KingDariaDu** [Steel-Dev/ItemQualities#15]
How can I change the plugin content to another language myself？I want to try to translate the quality of things into Chinese.
![image](https://user-images.githubusercontent.com/50005109/176649184-8033d009-be46-4b6d-bc9d-8ab43c209fd4.png)

**Comment by Steel-Dev** [comment]
Hm, these should be translated. I'll look into that. This looks like a bug.

**Comment by Sparky200** [comment]
You'll have to make a PR to add a language locale. The locales are in `src/main/resources`:
![image](https://user-images.githubusercontent.com/48421896/176798381-ee9e6931-6c8b-4a5c-be19-ed23b431c772.png)

**Comment by Steel-Dev** [comment]
What Sparky200 said ^
