### ISSUE TITLE
Item qualities description disappears after enchant

### ISSUE THREAD

**Issue by Barroncz** [Steel-Dev/ItemQualities#17]
Hello, i write you as you requested, images shows process when i try once again this bug. i found out that even if you put it to enchant everything but name disappear. No error in console. I know you wrote that it was fixed, i see that thats maybe not true or there is something else that make this bug.
![image](https://user-images.githubusercontent.com/5437586/177866897-0ff8507b-c572-4765-9ce9-37c7b470631c.png)
![image](https://user-images.githubusercontent.com/5437586/177867047-8a6b1320-d9f6-4d47-88bd-1b9d3171bd16.png)
![image](https://user-images.githubusercontent.com/5437586/177867150-9727d753-291c-4e57-bcaf-4830e88e441d.png)
![image](https://user-images.githubusercontent.com/5437586/177867331-8a3e3475-62bc-4fc3-ba71-932bd53bf4ed.png)
![image](https://user-images.githubusercontent.com/5437586/177867369-50204beb-56d6-4f7d-8698-f75835bf1a7d.png)
![image](https://user-images.githubusercontent.com/5437586/177867383-5f5b2608-cc1b-4510-bfd6-f712533cdbef.png)
![image](https://user-images.githubusercontent.com/5437586/177867405-6e4ca515-7e0a-4cb1-a00c-6162b5387bfb.png)

**Comment by Barroncz** [comment]
Maybe i found what do that, plugin for stacking items. I think it can be fixed if we remove or turn false stacking of tools and weapons etc. that can have enchants.

**Comment by Steel-Dev** [comment]
Legit fixed this in 1.1.0, but hey, of course it works perfectly on my end but breaks for other people. Just how it goes, I guess. (totally not annoyed lol)

I'll see why this is happening.

**Comment by Steel-Dev** [comment]
I'm unable to recreate this. It is indeed functioning perfectly

![opera_jhB2zMU9cR](https://user-images.githubusercontent.com/12509016/177887896-5e2728f3-46fb-4ad7-b003-07ef83d7a9ec.gif)
.

**Comment by Barroncz** [comment]
unfortunately nothing helped, we will try use more methods to fix it, but i think it will be no use, something rewrites lore of item... and i dont know what. but thank you.
