### ISSUE TITLE
NBT tags added to all items

### ISSUE THREAD

**Issue by AlexBrightwater** [Steel-Dev/ItemQualities#2]
Apparently, all items get an NBT Tag so the plugin knows it is handcrafted. This caused quite the confusion among players on my server since they were no longer able to stack items of the same type since only some had NBT data due to the fact, that some items existed before the plugin was added and before the option for only allowing looted items to have qualities was added.
Maybe there is a better way to implement this. :smile: 

`<censored name> has the following entity data: {id: "minecraft:oak_planks”, tag: {PublicBukkitValues: {"itemqualities:crafted"; 1}}, Count: 26b}`

**Comment by Steel-Dev** [comment]
oops! This was my bad, It's meant to only apply to tools. I'll fix this!

**Comment by Steel-Dev** [comment]
I've fixed the issue, check out [1.0.4.1 hotfix](https://www.spigotmc.org/resources/item-qualities.102350/update?update=460005).
