### ISSUE TITLE
Netherite Items are not changing

### ISSUE THREAD

**Issue by DerMFMonix** [Steel-Dev/ItemQualities#3]
When crafting a netherite sword out of a diamond sword, the netherite sword will be exactly the same as the diamond sword. No new quality and even the damage will be the same as diamond.

**Comment by DerMFMonix** [comment]
![2022-06-16_15 06 30](https://user-images.githubusercontent.com/106935863/174083277-d5dfb35f-c751-4712-bf82-26d77d5e4714.png)

It keeps the same damage and the name from the old sword.

**Comment by Steel-Dev** [comment]
I believe I have fixed all of these issues, would you mind testing it?

Download the fix [here](https://drive.google.com/file/d/1pVTIl-i04hayVSGo3WqUwKxaK_8YQdQw/view?usp=sharing).

Lemme know if everything is alright and I will publish it!

**Comment by Steel-Dev** [comment]
It doesn't get a quality because you have the craft option disabled, if you enable it, it will get one. Technically smithing is crafting :p

**Comment by Steel-Dev** [comment]
oh also, the double drops will effect anything that has a max stack size of more than 1 (so tools and such will not be effected) if you think I should make it to where the double drops only effects mobs, let me know!

Also, do you think I should make it to where if you have the quality on craft disabled when you smith, the result item should get the quality of the input item?

**Comment by Steel-Dev** [comment]
What do you mean reload feature? like a /reload command? There is one, /qualities reload

And alright, sounds good, I'll get those going.

**Comment by Steel-Dev** [comment]
I got those suggestions in now. Test them out [here](https://drive.google.com/file/d/1Sb3u2ZJ80syx1U8i_Z_nXP1Tqq_WwPln/view?usp=sharing).

Note, the double drop now only effects Mobs AND Animals. If you think I should add config options to better customize what it effects, let me know!

**Comment by Steel-Dev** [comment]
I'm going to assume everything is in order, on my end everything is fine! thanks for reporting these issues. I will be publishing this hotfix now. You may reopen this issue if you have anything else to say!
