### ISSUE TITLE
fortune....

### ISSUE THREAD

**Issue by nywmeta-ani** [Steel-Dev/ItemQualities#4]
makes fortune stop working

**Comment by Steel-Dev** [comment]
I'll get on it.

**Comment by Steel-Dev** [comment]
In my testing, it works fine?

**Comment by Steel-Dev** [comment]
Yeah, Fortune works perfectly fine on my end. With and without a pickaxe that has a Quality with Double Drops. Both apply perfectly.

What's the issue you're having with it? Please be a bit more descriptive.

**Comment by nywmeta-ani** [comment]
for me it completely seems to skip fortune and focuses on double drops alone

**Comment by nywmeta-ani** [comment]
i was thinking i had fortune on the pickaxe before i downloaded the plugin could that have broken it somehow

**Comment by nywmeta-ani** [comment]
it could also be that they dont stack in a good way primarily focusing on the double drop chance and then the 10% on"godly" would apply fortune

**Comment by nywmeta-ani** [comment]
i am also questioning if axe with sharpness works either because from the default config sharpness 5 godly d_axe fells like it does not do enough damage

**Comment by nywmeta-ani** [comment]
i am loving the plugin tho 👍

**Comment by Steel-Dev** [comment]
Okay I just went into a singleplayer world, no mods or anything and tested Fortune 1, 2 and 3.

Fortune 1 - Dropped 1 to 2 Diamonds.

Fortune 2 - Dropped 1 to 3 Diamonds.

Fortune 3 - Dropped 1 to 4 Diamonds.

Which matches my testing with the plugin, as well, except when Double Drops activated it of course doubled whatever the Fortune dropped.

**Comment by Steel-Dev** [comment]
I've fixed the Sharpness bug, and since fortune appears to be behaving properly and as intended, and I am unable to recreate the issue you are having with it, I will be closing this issue.

If you still believe you are having trouble with fortune, feel free to re-open this issue or create a new one.
