### ISSUE TITLE
Deleted files appear in directory after server restart

### ISSUE THREAD

**Issue by Synai13** [Steel-Dev/ItemQualities#5]
Hello, 

so like said in the title, when I delete files in the directory that came with the plugin, they reappear after every 2nd server restart. First picture is what I want to have and the second is when files reappear. How can I make them not reappear after deletion?

Hope you have any idea why this happens, otherwise I'm loving the plugin.

Best regards

![plugin as it should be](https://user-images.githubusercontent.com/107817054/174503079-0aebaf8e-b758-45e5-839d-64cc0a9389d2.png)
![plugin issue](https://user-images.githubusercontent.com/107817054/174503078-ada7a610-cea5-438e-ba8c-fd2e9730d3f9.png)

**Comment by Steel-Dev** [comment]
They should not re-appear after restart/reload if you disable example qualities in the Config. Do you have it enabled?

**Comment by Synai13** [comment]
Yeah that fixed it, thanks man.

**Comment by Steel-Dev** [comment]
Of course! Thanks for your report either way. Have a great day!
